version: '3'

services:
    app:
        build: .
        entrypoint: /var/www/html/docker-entrypoint.sh
        ports:
            - 8000:8000
            - 6001:6001
        volumes:
            - .:/var/www/html
        depends_on:
            - redis
    redis:
        image: redis:alpine
        ports:
            - 6379:6379